# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44f0f0f79437334e3334a8283fb8f1b9dec31758d5ccabdd698d703dce18016551a157054f001210f78d702065e05ac9ef168b854cb07eadadf51f98daa7e664

test:
  secret_key_base: 954c98d5ed316e3f95d54b6c9ab56a481f80840127ca6e48d03113a732ec6a22a3d6cc34ad3adc1e8270881e7ce11ab85d376b7bf77cd20b41eeb54bbc08aae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
